### ISSUE TITLE
Displaying temperature

### ISSUE THREAD

**Issue by tjspragg** [johnwargo/pi_weather_station#1]
Hi!

Thanks for sharing this code - it's really been a huge help! I've been struggling to adapt the code to show two digits that simply display the temperature. Any advice how / where / what to add?

Any advice would be very appreciated! :)

**Comment by johnwargo** [comment]
Did you look at the article mentioned in the beginning of the project's readme?  The readme has this in it:

Note: If you'd like to display one of the measurements on the display instead of the arrows this app uses, take a look at this: [http://yaab-arduino.blogspot.co.uk/2016/08/display-two-digits-numbers-on-raspberry.html](http://yaab-arduino.blogspot.co.uk/2016/08/display-two-digits-numbers-on-raspberry.html).

You basically have to make an array of LEDs for each number you want to display, and write the appropriate array to the display depending on what numbers you want to render. It's pretty straightforward.
