### ISSUE TITLE
pi_weather_station

### ISSUE THREAD

**Issue by ronadt** [johnwargo/pi_weather_station#6]
Rasp pi 4, python 2.x or 3.x
stops with this error: ImportError: cannot import name 'urlencode' from 'urllib' (/usr/lib/python3.7/urllib/__init__.py)
Can't find much info on this, I am very new to this...

**Comment by johnwargo** [comment]
I assume that you're running Python 2 for this project, because that's the default for Raspbian.  You're running Python 3 and I did a quick google search on the error message (which you should do any time you encounter an error) and came up with this: 
 https://stackoverflow.com/questions/44031471/importerror-cannot-import-name-urlencode-when-trying-to-install-flask-ext-sto

So you'll either run the server process using Python 2, or modify line 19 pf `weather_station.py` as described in the linked article.
