### ISSUE TITLE
Issue connecting to Wunder Underground 

### ISSUE THREAD

**Issue by thorpup** [johnwargo/pi_weather_station#8]
this is my error message i receive 

ERROR Exception type: <class 'list'>
2022-01-28 12:00:00 ERROR Error: <class 'AttributeError'>
Traceback (most recent call last):
  File "/home/pi/pi_weather_station/./weather_station.py", line 239, in processing_loop
    urllib.request.urlopen('http://weatherstation.wunderground.com/weatherstation/StationData.php?ID=StationID')
AttributeError: module 'urllib' has no attribute 'request'

not sure how to fix this.

**Comment by johnwargo** [comment]
A quick Google search gave me this: 

https://stackoverflow.com/questions/37042152/python-3-5-1-urllib-has-no-attribute-request

My code is pretty old, perhaps things changed a bit in the library since I wrote it.

**Comment by johnwargo** [comment]
@thorpup did that help you? Please respond at least to let me know I can close the issue.

**Comment by JumboSwart69** [comment]
HI
I know this is old but im getting this  error and im useless at these things
Traceback (most recent call last):
  File "/home/pi/pi_weather_station/weather_station.py", line 19, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode' from 'urllib' (/usr/lib/python3.9/urllib/__init__.py)

**Comment by JumboSwart69** [comment]
ok so not sure if im getting there but this is the last error im getting
   STATION_ID = IINHAM16
NameError: name 'IINHAM16' is not defined

**Comment by johnwargo** [comment]
@JumboSwart69 the first error is due to the fact that the `urlencode` method or object (I'm not sure) export is not in the current version of `urllib`. Often library authors change things around, sometimes moving big chunks of code into a new library. 

The second one means that you connected to the service, but the service couldn't find the Station you created. Double check the spelling of the `STATION_ID` constant in the `config.py` file. 

If you still need help, start a new issue, don't add on to an existing issue.
